### ISSUE TITLE
loading weights in main.py

### ISSUE THREAD

**Issue by aryan-gupta-data** [bfarzin/pytorch_aae#1]
Hi,
Could you please point to where the trained AdvAE weights are being loaded in main.py before the features are being classified into the MNIST classes?
Thanks

**Comment by bfarzin** [comment]
It is not loaded; that is a bug.  It should go on line 61 before `Q.eval()`
The line should be `Q.load_state_dict(torch.load('Q_encoder_weights.pt'))` 
I will fix and re-post the update.  Thanks for pointing this out.

**Comment by aryan-gupta-data** [comment]
Thx for the reply.
I edited the code...should I send a pull request to update the repo and you could merge it.

**Comment by bfarzin** [comment]
It was easy enough. I pushed out the change.  Let me know if you a have any other issues and thanks for looking at the code!  I hope it helps you out in some way.
