### ISSUE TITLE
Confusion about part of the concept 

### ISSUE THREAD

**Issue by ferric123** [bfarzin/pytorch_aae#4]
Hello, in sampling a random gaussian latent vector, could you please tell me why you multiply it by 5 using 

> Variable(torch.randn(images.size()[0], z_red_dims) * 5.).cuda()

 instead of ,

> Variable(torch.randn(images.size()[0], z_red_dims) ).cuda()

Moreover, in this case we cannot ensure each dimension of latent vector to be a tensor in range (0,1). My confusion is, how can the gaussian discriminator still work without a normalized gaussian vector or latent vector as its input?

**Comment by bfarzin** [comment]
I am not sure what the right answer is to this.  When I went back to the blog I was looking at to view this, I found that they had sampled from N(0,5)  But I can't tell you why.  does it work (or work better) with N(0,1)?

Here is a link to the blog:
https://blog.paperspace.com/adversarial-autoencoders-with-pytorch/
